-- Account-owned shopping lists. The app writes audit fields explicitly;
-- this migration does not create triggers or RPC functions.
create table if not exists public.shopping_list (
  id bigint generated by default as identity not null,
  account_id bigint not null,
  name character varying not null,
  created_at timestamp with time zone not null default now(),
  created_by bigint not null,
  updated_at timestamp with time zone not null default now(),
  updated_by bigint not null,
  deleted_at timestamp with time zone null,
  deleted_by bigint null,
  constraint shopping_list_pkey primary key (id),
  constraint shopping_list_name_not_blank check (btrim(name) <> ''),
  constraint shopping_list_account_id_fkey foreign key (account_id)
    references public.account (id) on update cascade on delete cascade,
  constraint shopping_list_created_by_fkey foreign key (created_by)
    references public.account (id) on update cascade,
  constraint shopping_list_updated_by_fkey foreign key (updated_by)
    references public.account (id) on update cascade,
  constraint shopping_list_deleted_by_fkey foreign key (deleted_by)
    references public.account (id) on update cascade
);

create unique index if not exists shopping_list_active_name_key
  on public.shopping_list (account_id, lower(btrim(name)))
  where deleted_at is null;

create index if not exists shopping_list_account_id_idx
  on public.shopping_list (account_id)
  where deleted_at is null;

create table if not exists public.shopping_list_item (
  id bigint generated by default as identity not null,
  shopping_list_id bigint not null,
  ingredient_id bigint null,
  name character varying not null,
  amount double precision null,
  unit character varying null,
  note character varying null,
  checked boolean not null default false,
  created_at timestamp with time zone not null default now(),
  created_by bigint not null,
  updated_at timestamp with time zone not null default now(),
  updated_by bigint not null,
  deleted_at timestamp with time zone null,
  deleted_by bigint null,
  constraint shopping_list_item_pkey primary key (id),
  constraint shopping_list_item_name_not_blank check (btrim(name) <> ''),
  constraint shopping_list_item_amount_positive check (
    amount is null or amount > 0
  ),
  constraint shopping_list_item_unit_requires_amount check (
    unit is null or amount is not null
  ),
  constraint shopping_list_item_list_id_fkey foreign key (shopping_list_id)
    references public.shopping_list (id) on update cascade on delete cascade,
  constraint shopping_list_item_ingredient_id_fkey foreign key (ingredient_id)
    references public.ingredient (id) on update cascade on delete set null,
  constraint shopping_list_item_unit_fkey foreign key (unit)
    references public.unit (code) on update cascade,
  constraint shopping_list_item_created_by_fkey foreign key (created_by)
    references public.account (id) on update cascade,
  constraint shopping_list_item_updated_by_fkey foreign key (updated_by)
    references public.account (id) on update cascade,
  constraint shopping_list_item_deleted_by_fkey foreign key (deleted_by)
    references public.account (id) on update cascade
);

-- Quantities such as "5 cucumbers" are valid without an explicit unit.
alter table public.shopping_list_item
  drop constraint if exists shopping_list_item_amount_unit_pair;

do $$
begin
  if not exists (
    select 1 from pg_constraint
    where conname = 'shopping_list_item_unit_requires_amount'
      and conrelid = 'public.shopping_list_item'::regclass
  ) then
    alter table public.shopping_list_item
      add constraint shopping_list_item_unit_requires_amount
      check (unit is null or amount is not null);
  end if;
end
$$;

create index if not exists shopping_list_item_list_id_idx
  on public.shopping_list_item (shopping_list_id, checked, created_at)
  where deleted_at is null;

alter table public.shopping_list_item
  add column if not exists note character varying null;

-- Experimental supermarket grouping. This section is intentionally isolated
-- so it can be removed again if category grouping is not useful in practice.
create table if not exists public.shopping_category (
  code character varying not null,
  name_en character varying not null,
  name_de character varying not null,
  sort_order integer not null,
  created_at timestamp with time zone not null default now(),
  created_by bigint not null default 1,
  updated_at timestamp with time zone not null default now(),
  updated_by bigint not null default 1,
  deleted_at timestamp with time zone null,
  deleted_by bigint null,
  constraint shopping_category_pkey primary key (code),
  constraint shopping_category_created_by_fkey foreign key (created_by)
    references public.account (id) on update cascade,
  constraint shopping_category_updated_by_fkey foreign key (updated_by)
    references public.account (id) on update cascade,
  constraint shopping_category_deleted_by_fkey foreign key (deleted_by)
    references public.account (id) on update cascade
);

insert into public.shopping_category (code, name_en, name_de, sort_order)
values
  ('produce', 'Fruit & Vegetables', 'Obst & Gemüse', 10),
  ('bakery', 'Bakery', 'Bäckerei', 20),
  ('dairy_eggs', 'Dairy & Eggs', 'Milchprodukte & Eier', 30),
  ('meat_fish', 'Meat & Fish', 'Fleisch & Fisch', 40),
  ('pantry', 'Pantry', 'Vorrat', 50),
  ('frozen', 'Frozen', 'Tiefkühlkost', 60),
  ('drinks', 'Drinks', 'Getränke', 70),
  ('household', 'Household', 'Haushalt', 80),
  ('other', 'Other', 'Sonstiges', 90)
on conflict (code) do update set
  name_en = excluded.name_en,
  name_de = excluded.name_de,
  sort_order = excluded.sort_order,
  updated_at = now(),
  updated_by = 1,
  deleted_at = null,
  deleted_by = null;

alter table public.ingredient
  add column if not exists shopping_category_code character varying null;

alter table public.shopping_list_item
  add column if not exists shopping_category_code character varying;

update public.shopping_list_item
set shopping_category_code = 'other'
where shopping_category_code is null;

alter table public.shopping_list_item
  alter column shopping_category_code set default 'other',
  alter column shopping_category_code set not null;

do $$
begin
  if not exists (
    select 1 from pg_constraint
    where conname = 'ingredient_shopping_category_fkey'
      and conrelid = 'public.ingredient'::regclass
  ) then
    alter table public.ingredient
      add constraint ingredient_shopping_category_fkey
      foreign key (shopping_category_code)
      references public.shopping_category (code)
      on update cascade;
  end if;

  if not exists (
    select 1 from pg_constraint
    where conname = 'shopping_list_item_category_fkey'
      and conrelid = 'public.shopping_list_item'::regclass
  ) then
    alter table public.shopping_list_item
      add constraint shopping_list_item_category_fkey
      foreign key (shopping_category_code)
      references public.shopping_category (code)
      on update cascade;
  end if;
end
$$;
