-- Meal-plan servings, week copying, and account-owned reusable templates.
-- Run this entire file in the Supabase SQL Editor.
begin;

alter table public.recipe
  add column if not exists servings integer null;

alter table public.meal_plan_entry
  add column if not exists servings integer null;

do $$
begin
  if not exists (
    select 1 from pg_constraint
    where conname = 'recipe_servings_positive'
      and conrelid = 'public.recipe'::regclass
  ) then
    alter table public.recipe
      add constraint recipe_servings_positive
      check (servings is null or servings > 0);
  end if;

  if not exists (
    select 1 from pg_constraint
    where conname = 'meal_plan_entry_servings_positive'
      and conrelid = 'public.meal_plan_entry'::regclass
  ) then
    alter table public.meal_plan_entry
      add constraint meal_plan_entry_servings_positive
      check (servings is null or servings > 0);
  end if;
end;
$$;

create table if not exists public.meal_plan_template (
  id bigint generated by default as identity not null,
  account_id bigint not null,
  name character varying not null,
  created_at timestamp with time zone not null default now(),
  created_by bigint not null,
  updated_at timestamp with time zone not null default now(),
  updated_by bigint not null,
  deleted_at timestamp with time zone null,
  deleted_by bigint null,
  constraint meal_plan_template_pkey primary key (id),
  constraint meal_plan_template_name_not_blank check (btrim(name) <> ''),
  constraint meal_plan_template_account_id_fkey foreign key (account_id)
    references public.account (id) on update cascade on delete cascade,
  constraint meal_plan_template_created_by_fkey foreign key (created_by)
    references public.account (id) on update cascade,
  constraint meal_plan_template_updated_by_fkey foreign key (updated_by)
    references public.account (id) on update cascade,
  constraint meal_plan_template_deleted_by_fkey foreign key (deleted_by)
    references public.account (id) on update cascade
);

create table if not exists public.meal_plan_template_entry (
  id bigint generated by default as identity not null,
  template_id bigint not null,
  day_offset integer not null,
  meal_slot character varying not null,
  recipe_id bigint null,
  recipe_title_snapshot character varying null,
  custom_title character varying null,
  note character varying null,
  servings integer null,
  sort_order integer not null default 0,
  created_at timestamp with time zone not null default now(),
  created_by bigint not null,
  updated_at timestamp with time zone not null default now(),
  updated_by bigint not null,
  deleted_at timestamp with time zone null,
  deleted_by bigint null,
  constraint meal_plan_template_entry_pkey primary key (id),
  constraint meal_plan_template_entry_template_id_fkey foreign key (template_id)
    references public.meal_plan_template (id)
    on update cascade on delete cascade,
  constraint meal_plan_template_entry_recipe_id_fkey foreign key (recipe_id)
    references public.recipe (id) on update cascade on delete set null,
  constraint meal_plan_template_entry_created_by_fkey foreign key (created_by)
    references public.account (id) on update cascade,
  constraint meal_plan_template_entry_updated_by_fkey foreign key (updated_by)
    references public.account (id) on update cascade,
  constraint meal_plan_template_entry_deleted_by_fkey foreign key (deleted_by)
    references public.account (id) on update cascade,
  constraint meal_plan_template_entry_day_check check (
    day_offset between 0 and 6
  ),
  constraint meal_plan_template_entry_slot_check check (
    meal_slot in ('breakfast', 'lunch', 'dinner', 'snack')
  ),
  constraint meal_plan_template_entry_content_check check (
    (recipe_id is not null and custom_title is null) or
    (recipe_id is null and custom_title is not null and btrim(custom_title) <> '') or
    (recipe_id is null and custom_title is null and
      nullif(btrim(recipe_title_snapshot), '') is not null)
  ),
  constraint meal_plan_template_entry_servings_positive check (
    servings is null or servings > 0
  ),
  constraint meal_plan_template_entry_sort_order_check check (sort_order >= 0)
);

create index if not exists meal_plan_template_entry_template_idx
  on public.meal_plan_template_entry
    (template_id, day_offset, meal_slot, sort_order)
  where deleted_at is null;

create or replace function public.owns_meal_plan_template(
  p_template_id bigint
)
returns boolean
language sql
stable
security definer
set search_path = ''
as $$
  select exists (
    select 1
    from public.meal_plan_template
    where id = p_template_id
      and account_id = public.current_account_id()
      and deleted_at is null
  )
$$;

alter table public.meal_plan_template enable row level security;
alter table public.meal_plan_template_entry enable row level security;

drop policy if exists meal_plan_template_private_own
  on public.meal_plan_template;
create policy meal_plan_template_private_own
on public.meal_plan_template for all to authenticated
using (account_id = public.current_account_id())
with check (
  public.current_account_can_write()
  and account_id = public.current_account_id()
  and created_by = public.current_account_id()
  and updated_by = public.current_account_id()
);

drop policy if exists meal_plan_template_entry_private_own
  on public.meal_plan_template_entry;
create policy meal_plan_template_entry_private_own
on public.meal_plan_template_entry for all to authenticated
using (public.owns_meal_plan_template(template_id))
with check (
  public.current_account_can_write()
  and public.owns_meal_plan_template(template_id)
  and created_by = public.current_account_id()
  and updated_by = public.current_account_id()
);

revoke all on function public.owns_meal_plan_template(bigint)
  from public, anon;

grant execute on function public.owns_meal_plan_template(bigint)
  to authenticated;

notify pgrst, 'reload schema';
commit;
