-- Adds shared store sections to shopping lists.
-- Run this once in the Supabase SQL Editor before using the feature.
-- Existing items remain in the app's built-in "General" section because
-- section_id is nullable. This migration does not create any triggers.

begin;

create table if not exists public.shopping_list_section (
  id bigint generated by default as identity not null,
  shopping_list_id bigint not null,
  name character varying not null,
  sort_order integer not null default 0,
  created_at timestamp with time zone not null,
  created_by bigint not null,
  updated_at timestamp with time zone not null,
  updated_by bigint not null,
  deleted_at timestamp with time zone null,
  deleted_by bigint null,
  constraint shopping_list_section_pkey primary key (id),
  constraint shopping_list_section_name_not_blank
    check (btrim(name) <> ''),
  constraint shopping_list_section_sort_order_nonnegative
    check (sort_order >= 0),
  constraint shopping_list_section_list_fkey
    foreign key (shopping_list_id) references public.shopping_list (id)
    on update cascade on delete cascade,
  constraint shopping_list_section_created_by_fkey
    foreign key (created_by) references public.account (id)
    on update cascade,
  constraint shopping_list_section_updated_by_fkey
    foreign key (updated_by) references public.account (id)
    on update cascade,
  constraint shopping_list_section_deleted_by_fkey
    foreign key (deleted_by) references public.account (id)
    on update cascade
);

alter table public.shopping_list_item
  add column if not exists section_id bigint null;

do $$
begin
  if not exists (
    select 1
    from pg_constraint
    where conname = 'shopping_list_item_section_id_fkey'
      and conrelid = 'public.shopping_list_item'::regclass
  ) then
    alter table public.shopping_list_item
      add constraint shopping_list_item_section_id_fkey
      foreign key (section_id)
      references public.shopping_list_section (id)
      on update cascade on delete set null;
  end if;
end
$$;

create index if not exists shopping_list_section_list_order_idx
  on public.shopping_list_section (shopping_list_id, sort_order, id);
create index if not exists shopping_list_item_section_idx
  on public.shopping_list_item (section_id);

alter table public.shopping_list_section enable row level security;

drop policy if exists shopping_list_section_shared_read
  on public.shopping_list_section;
create policy shopping_list_section_shared_read
  on public.shopping_list_section
  for select to authenticated
  using (public.can_view_shopping_list(shopping_list_id));

drop policy if exists shopping_list_section_shared_write
  on public.shopping_list_section;
create policy shopping_list_section_shared_write
  on public.shopping_list_section
  for all to authenticated
  using (public.can_edit_shopping_list(shopping_list_id))
  with check (
    public.can_edit_shopping_list(shopping_list_id)
    and updated_by = public.current_account_id()
  );

-- Keep an item and its store section inside the same shopping list.
drop policy if exists shopping_list_item_shared_write
  on public.shopping_list_item;
create policy shopping_list_item_shared_write
  on public.shopping_list_item
  for all to authenticated
  using (public.can_edit_shopping_list(shopping_list_id))
  with check (
    public.can_edit_shopping_list(shopping_list_id)
    and updated_by = public.current_account_id()
    and (
      shopping_list_item.section_id is null
      or exists (
        select 1
        from public.shopping_list_section as section
        where section.id = shopping_list_item.section_id
          and section.shopping_list_id =
              shopping_list_item.shopping_list_id
          and section.deleted_at is null
      )
    )
  );

revoke all on public.shopping_list_section from anon, authenticated;
grant select, insert, update, delete
  on public.shopping_list_section to authenticated;
grant usage, select
  on sequence public.shopping_list_section_id_seq to authenticated;

do $$
begin
  if not exists (
    select 1
    from pg_publication_tables
    where pubname = 'supabase_realtime'
      and schemaname = 'public'
      and tablename = 'shopping_list_section'
  ) then
    alter publication supabase_realtime
      add table public.shopping_list_section;
  end if;
end
$$;

notify pgrst, 'reload schema';

commit;
