-- Shared shopping lists and meal plans with explicit invitations.
-- Existing profile-based meal plans are migrated without triggers.
begin;

create table if not exists public.meal_plan (
  id bigint generated by default as identity not null,
  account_id bigint not null,
  name character varying not null,
  created_at timestamp with time zone not null default now(),
  created_by bigint not null,
  updated_at timestamp with time zone not null default now(),
  updated_by bigint not null,
  deleted_at timestamp with time zone null,
  deleted_by bigint null,
  constraint meal_plan_pkey primary key (id),
  constraint meal_plan_name_not_blank check (btrim(name) <> ''),
  constraint meal_plan_account_fkey foreign key (account_id)
    references public.account (id) on update cascade on delete cascade,
  constraint meal_plan_created_by_fkey foreign key (created_by)
    references public.account (id) on update cascade,
  constraint meal_plan_updated_by_fkey foreign key (updated_by)
    references public.account (id) on update cascade,
  constraint meal_plan_deleted_by_fkey foreign key (deleted_by)
    references public.account (id) on update cascade
);

insert into public.meal_plan (
  id, account_id, name, created_at, created_by, updated_at, updated_by,
  deleted_at, deleted_by
)
select
  profile.id, profile.account_id, profile.name, profile.created_at,
  profile.created_by, profile.updated_at, profile.updated_by,
  profile.deleted_at, profile.deleted_by
from public.profiles as profile
on conflict (id) do nothing;

do $$
begin
  perform setval(
    pg_get_serial_sequence('public.meal_plan', 'id'),
    greatest(coalesce((select max(id) from public.meal_plan), 1), 1),
    true
  );
end
$$;

create table if not exists public.meal_plan_entry (
  id bigint generated by default as identity not null,
  meal_plan_id bigint not null,
  planned_date date not null,
  meal_slot character varying not null,
  recipe_id bigint null,
  recipe_title_snapshot character varying null,
  custom_title character varying null,
  note character varying null,
  servings integer null,
  sort_order integer not null default 0,
  created_at timestamp with time zone not null default now(),
  created_by bigint not null,
  updated_at timestamp with time zone not null default now(),
  updated_by bigint not null,
  deleted_at timestamp with time zone null,
  deleted_by bigint null,
  constraint meal_plan_entry_pkey primary key (id),
  constraint meal_plan_entry_plan_fkey foreign key (meal_plan_id)
    references public.meal_plan (id) on update cascade on delete cascade,
  constraint meal_plan_entry_recipe_id_fkey foreign key (recipe_id)
    references public.recipe (id) on update cascade on delete set null,
  constraint meal_plan_entry_created_by_fkey foreign key (created_by)
    references public.account (id) on update cascade,
  constraint meal_plan_entry_updated_by_fkey foreign key (updated_by)
    references public.account (id) on update cascade,
  constraint meal_plan_entry_deleted_by_fkey foreign key (deleted_by)
    references public.account (id) on update cascade
);

alter table public.meal_plan_entry
  add column if not exists meal_plan_id bigint;

do $$
begin
  if exists (
    select 1 from information_schema.columns
    where table_schema = 'public'
      and table_name = 'meal_plan_entry'
      and column_name = 'profile_id'
  ) then
    execute $migration$
      update public.meal_plan_entry
      set meal_plan_id = profile_id
      where meal_plan_id is null
    $migration$;
  end if;
end
$$;

drop policy if exists meal_plan_entry_private_own
  on public.meal_plan_entry;
alter table public.meal_plan_entry
  drop constraint if exists meal_plan_entry_profile_id_fkey;
alter table public.meal_plan_entry
  alter column meal_plan_id set not null;

do $$
begin
  if not exists (
    select 1 from pg_constraint
    where conname = 'meal_plan_entry_plan_fkey'
      and conrelid = 'public.meal_plan_entry'::regclass
  ) then
    alter table public.meal_plan_entry
      add constraint meal_plan_entry_plan_fkey
      foreign key (meal_plan_id) references public.meal_plan (id)
      on update cascade on delete cascade;
  end if;
end
$$;

alter table public.meal_plan_entry drop column if exists profile_id;
drop index if exists public.meal_plan_entry_profile_date_idx;
create index if not exists meal_plan_entry_plan_date_idx
  on public.meal_plan_entry
    (meal_plan_id, planned_date, meal_slot, sort_order)
  where deleted_at is null;

create table if not exists public.shopping_list_member (
  shopping_list_id bigint not null,
  account_id bigint not null,
  permission character varying not null,
  status character varying not null default 'accepted',
  created_at timestamp with time zone not null default now(),
  created_by bigint not null,
  updated_at timestamp with time zone not null default now(),
  updated_by bigint not null,
  deleted_at timestamp with time zone null,
  deleted_by bigint null,
  constraint shopping_list_member_pkey
    primary key (shopping_list_id, account_id),
  constraint shopping_list_member_permission_check
    check (permission in ('viewer', 'editor')),
  constraint shopping_list_member_status_check
    check (status in ('pending', 'accepted', 'declined')),
  constraint shopping_list_member_list_fkey foreign key (shopping_list_id)
    references public.shopping_list (id) on update cascade on delete cascade,
  constraint shopping_list_member_account_fkey foreign key (account_id)
    references public.account (id) on update cascade on delete cascade,
  constraint shopping_list_member_created_by_fkey foreign key (created_by)
    references public.account (id) on update cascade,
  constraint shopping_list_member_updated_by_fkey foreign key (updated_by)
    references public.account (id) on update cascade,
  constraint shopping_list_member_deleted_by_fkey foreign key (deleted_by)
    references public.account (id) on update cascade
);

create table if not exists public.meal_plan_member (
  meal_plan_id bigint not null,
  account_id bigint not null,
  permission character varying not null,
  status character varying not null default 'accepted',
  created_at timestamp with time zone not null default now(),
  created_by bigint not null,
  updated_at timestamp with time zone not null default now(),
  updated_by bigint not null,
  deleted_at timestamp with time zone null,
  deleted_by bigint null,
  constraint meal_plan_member_pkey primary key (meal_plan_id, account_id),
  constraint meal_plan_member_permission_check
    check (permission in ('viewer', 'editor')),
  constraint meal_plan_member_status_check
    check (status in ('pending', 'accepted', 'declined')),
  constraint meal_plan_member_plan_fkey foreign key (meal_plan_id)
    references public.meal_plan (id) on update cascade on delete cascade,
  constraint meal_plan_member_account_fkey foreign key (account_id)
    references public.account (id) on update cascade on delete cascade,
  constraint meal_plan_member_created_by_fkey foreign key (created_by)
    references public.account (id) on update cascade,
  constraint meal_plan_member_updated_by_fkey foreign key (updated_by)
    references public.account (id) on update cascade,
  constraint meal_plan_member_deleted_by_fkey foreign key (deleted_by)
    references public.account (id) on update cascade
);

alter table public.shopping_list_member
  add column if not exists status character varying not null
  default 'accepted';
alter table public.meal_plan_member
  add column if not exists status character varying not null
  default 'accepted';

do $$
begin
  if not exists (
    select 1 from pg_constraint
    where conname = 'shopping_list_member_status_check'
      and conrelid = 'public.shopping_list_member'::regclass
  ) then
    alter table public.shopping_list_member
      add constraint shopping_list_member_status_check
      check (status in ('pending', 'accepted', 'declined'));
  end if;
  if not exists (
    select 1 from pg_constraint
    where conname = 'meal_plan_member_status_check'
      and conrelid = 'public.meal_plan_member'::regclass
  ) then
    alter table public.meal_plan_member
      add constraint meal_plan_member_status_check
      check (status in ('pending', 'accepted', 'declined'));
  end if;
end
$$;

create or replace function public.can_discover_shopping_list(p_list_id bigint)
returns boolean language sql stable security definer set search_path = '' as $$
  select exists (
    select 1 from public.shopping_list as list
    where list.id = p_list_id
      and list.deleted_at is null
      and (
        list.account_id = public.current_account_id()
        or exists (
          select 1 from public.shopping_list_member as member
          where member.shopping_list_id = list.id
            and member.account_id = public.current_account_id()
            and member.status in ('pending', 'accepted')
            and member.deleted_at is null
        )
      )
  )
$$;

create or replace function public.can_view_shopping_list(p_list_id bigint)
returns boolean language sql stable security definer set search_path = '' as $$
  select exists (
    select 1 from public.shopping_list as list
    where list.id = p_list_id
      and list.deleted_at is null
      and (
        list.account_id = public.current_account_id()
        or exists (
          select 1 from public.shopping_list_member as member
          where member.shopping_list_id = list.id
            and member.account_id = public.current_account_id()
            and member.status = 'accepted'
            and member.deleted_at is null
        )
      )
  )
$$;

create or replace function public.can_edit_shopping_list(p_list_id bigint)
returns boolean language sql stable security definer set search_path = '' as $$
  select public.current_account_can_write() and exists (
    select 1 from public.shopping_list as list
    where list.id = p_list_id
      and list.deleted_at is null
      and (
        list.account_id = public.current_account_id()
        or exists (
          select 1 from public.shopping_list_member as member
          where member.shopping_list_id = list.id
            and member.account_id = public.current_account_id()
            and member.permission = 'editor'
            and member.status = 'accepted'
            and member.deleted_at is null
        )
      )
  )
$$;

create or replace function public.can_discover_meal_plan(p_plan_id bigint)
returns boolean language sql stable security definer set search_path = '' as $$
  select exists (
    select 1 from public.meal_plan as plan
    where plan.id = p_plan_id
      and plan.deleted_at is null
      and (
        plan.account_id = public.current_account_id()
        or exists (
          select 1 from public.meal_plan_member as member
          where member.meal_plan_id = plan.id
            and member.account_id = public.current_account_id()
            and member.status in ('pending', 'accepted')
            and member.deleted_at is null
        )
      )
  )
$$;

create or replace function public.can_view_meal_plan(p_plan_id bigint)
returns boolean language sql stable security definer set search_path = '' as $$
  select exists (
    select 1 from public.meal_plan as plan
    where plan.id = p_plan_id
      and plan.deleted_at is null
      and (
        plan.account_id = public.current_account_id()
        or exists (
          select 1 from public.meal_plan_member as member
          where member.meal_plan_id = plan.id
            and member.account_id = public.current_account_id()
            and member.status = 'accepted'
            and member.deleted_at is null
        )
      )
  )
$$;

create or replace function public.can_edit_meal_plan(p_plan_id bigint)
returns boolean language sql stable security definer set search_path = '' as $$
  select public.current_account_can_write() and exists (
    select 1 from public.meal_plan as plan
    where plan.id = p_plan_id
      and plan.deleted_at is null
      and (
        plan.account_id = public.current_account_id()
        or exists (
          select 1 from public.meal_plan_member as member
          where member.meal_plan_id = plan.id
            and member.account_id = public.current_account_id()
            and member.permission = 'editor'
            and member.status = 'accepted'
            and member.deleted_at is null
        )
      )
  )
$$;

create or replace function public.set_shopping_list_member(
  p_shopping_list_id bigint,
  p_member_account_id bigint,
  p_permission text,
  p_remove boolean default false
)
returns void language plpgsql security definer set search_path = '' as $$
declare
  v_account_id bigint := public.current_account_id();
  v_now timestamp with time zone := now();
begin
  if v_account_id is null or p_member_account_id = v_account_id then
    raise exception 'invalid_shopping_list_member';
  end if;
  if p_permission not in ('viewer', 'editor') then
    raise exception 'invalid_shopping_list_permission';
  end if;
  if not exists (
    select 1 from public.account_friend
    where first_account_id = least(v_account_id, p_member_account_id)
      and second_account_id = greatest(v_account_id, p_member_account_id)
      and status = 'accepted'
      and deleted_at is null
  ) then
    raise exception 'accepted_friend_required';
  end if;
  if not exists (
    select 1 from public.shopping_list
    where id = p_shopping_list_id
      and account_id = v_account_id
      and deleted_at is null
  ) then
    raise exception 'shopping_list_owner_required';
  end if;

  if p_remove then
    update public.shopping_list_member
    set updated_at = v_now,
        updated_by = v_account_id,
        deleted_at = v_now,
        deleted_by = v_account_id
    where shopping_list_id = p_shopping_list_id
      and account_id = p_member_account_id;
    return;
  end if;

  insert into public.shopping_list_member as member (
    shopping_list_id, account_id, permission, status,
    created_at, created_by, updated_at, updated_by, deleted_at, deleted_by
  ) values (
    p_shopping_list_id, p_member_account_id, p_permission, 'pending',
    v_now, v_account_id, v_now, v_account_id, null, null
  )
  on conflict (shopping_list_id, account_id) do update
  set permission = excluded.permission,
      status = case
        when member.deleted_at is null and member.status = 'accepted'
          then 'accepted'
        else 'pending'
      end,
      updated_at = excluded.updated_at,
      updated_by = excluded.updated_by,
      deleted_at = null,
      deleted_by = null;
end
$$;

create or replace function public.respond_shopping_list_invitation(
  p_shopping_list_id bigint,
  p_accept boolean
)
returns void language plpgsql security definer set search_path = '' as $$
declare
  v_account_id bigint := public.current_account_id();
  v_now timestamp with time zone := now();
begin
  if v_account_id is null then return; end if;
  update public.shopping_list_member
  set status = case when p_accept then 'accepted' else 'declined' end,
      updated_at = v_now,
      updated_by = v_account_id,
      deleted_at = case when p_accept then null else v_now end,
      deleted_by = case when p_accept then null else v_account_id end
  where shopping_list_id = p_shopping_list_id
    and account_id = v_account_id
    and status = 'pending'
    and deleted_at is null;
end
$$;

create or replace function public.set_meal_plan_member(
  p_meal_plan_id bigint,
  p_member_account_id bigint,
  p_permission text,
  p_remove boolean default false
)
returns void language plpgsql security definer set search_path = '' as $$
declare
  v_account_id bigint := public.current_account_id();
  v_now timestamp with time zone := now();
begin
  if v_account_id is null or p_member_account_id = v_account_id then
    raise exception 'invalid_meal_plan_member';
  end if;
  if p_permission not in ('viewer', 'editor') then
    raise exception 'invalid_meal_plan_permission';
  end if;
  if not exists (
    select 1 from public.account_friend
    where first_account_id = least(v_account_id, p_member_account_id)
      and second_account_id = greatest(v_account_id, p_member_account_id)
      and status = 'accepted'
      and deleted_at is null
  ) then
    raise exception 'accepted_friend_required';
  end if;
  if not exists (
    select 1 from public.meal_plan
    where id = p_meal_plan_id
      and account_id = v_account_id
      and deleted_at is null
  ) then
    raise exception 'meal_plan_owner_required';
  end if;

  if p_remove then
    update public.meal_plan_member
    set updated_at = v_now,
        updated_by = v_account_id,
        deleted_at = v_now,
        deleted_by = v_account_id
    where meal_plan_id = p_meal_plan_id
      and account_id = p_member_account_id;
    return;
  end if;

  insert into public.meal_plan_member as member (
    meal_plan_id, account_id, permission, status,
    created_at, created_by, updated_at, updated_by, deleted_at, deleted_by
  ) values (
    p_meal_plan_id, p_member_account_id, p_permission, 'pending',
    v_now, v_account_id, v_now, v_account_id, null, null
  )
  on conflict (meal_plan_id, account_id) do update
  set permission = excluded.permission,
      status = case
        when member.deleted_at is null and member.status = 'accepted'
          then 'accepted'
        else 'pending'
      end,
      updated_at = excluded.updated_at,
      updated_by = excluded.updated_by,
      deleted_at = null,
      deleted_by = null;
end
$$;

create or replace function public.respond_meal_plan_invitation(
  p_meal_plan_id bigint,
  p_accept boolean
)
returns void language plpgsql security definer set search_path = '' as $$
declare
  v_account_id bigint := public.current_account_id();
  v_now timestamp with time zone := now();
begin
  if v_account_id is null then return; end if;
  update public.meal_plan_member
  set status = case when p_accept then 'accepted' else 'declined' end,
      updated_at = v_now,
      updated_by = v_account_id,
      deleted_at = case when p_accept then null else v_now end,
      deleted_by = case when p_accept then null else v_account_id end
  where meal_plan_id = p_meal_plan_id
    and account_id = v_account_id
    and status = 'pending'
    and deleted_at is null;
end
$$;

create table if not exists public.account_friend (
  first_account_id bigint not null,
  second_account_id bigint not null,
  requested_by bigint not null,
  status character varying not null default 'pending',
  created_at timestamp with time zone not null default now(),
  created_by bigint not null,
  updated_at timestamp with time zone not null default now(),
  updated_by bigint not null,
  deleted_at timestamp with time zone null,
  deleted_by bigint null,
  constraint account_friend_pkey
    primary key (first_account_id, second_account_id),
  constraint account_friend_order_check
    check (first_account_id < second_account_id),
  constraint account_friend_requester_check
    check (requested_by in (first_account_id, second_account_id)),
  constraint account_friend_status_check
    check (status in ('pending', 'accepted', 'declined')),
  constraint account_friend_first_fkey foreign key (first_account_id)
    references public.account (id) on update cascade on delete cascade,
  constraint account_friend_second_fkey foreign key (second_account_id)
    references public.account (id) on update cascade on delete cascade,
  constraint account_friend_requested_by_fkey foreign key (requested_by)
    references public.account (id) on update cascade,
  constraint account_friend_created_by_fkey foreign key (created_by)
    references public.account (id) on update cascade,
  constraint account_friend_updated_by_fkey foreign key (updated_by)
    references public.account (id) on update cascade,
  constraint account_friend_deleted_by_fkey foreign key (deleted_by)
    references public.account (id) on update cascade
);

create or replace function public.send_friend_request(p_friend_account_id bigint)
returns void language plpgsql security definer set search_path = '' as $$
declare
  v_account_id bigint := public.current_account_id();
  v_first bigint;
  v_second bigint;
  v_now timestamp with time zone := now();
begin
  if v_account_id is null or p_friend_account_id = v_account_id then
    raise exception 'invalid_friend_account';
  end if;
  if not exists (
    select 1 from public.account
    where id = p_friend_account_id and deleted_at is null
  ) then
    raise exception 'friend_account_not_found';
  end if;
  v_first := least(v_account_id, p_friend_account_id);
  v_second := greatest(v_account_id, p_friend_account_id);
  insert into public.account_friend as friendship (
    first_account_id, second_account_id, requested_by, status,
    created_at, created_by, updated_at, updated_by, deleted_at, deleted_by
  ) values (
    v_first, v_second, v_account_id, 'pending',
    v_now, v_account_id, v_now, v_account_id, null, null
  )
  on conflict (first_account_id, second_account_id) do update
  set requested_by = excluded.requested_by,
      status = 'pending',
      updated_at = excluded.updated_at,
      updated_by = excluded.updated_by,
      deleted_at = null,
      deleted_by = null
  where friendship.deleted_at is not null
     or friendship.status = 'declined';
end
$$;

create or replace function public.respond_friend_request(
  p_requester_account_id bigint,
  p_accept boolean
)
returns void language plpgsql security definer set search_path = '' as $$
declare
  v_account_id bigint := public.current_account_id();
  v_now timestamp with time zone := now();
begin
  if v_account_id is null then return; end if;
  update public.account_friend
  set status = case when p_accept then 'accepted' else 'declined' end,
      updated_at = v_now,
      updated_by = v_account_id,
      deleted_at = case when p_accept then null else v_now end,
      deleted_by = case when p_accept then null else v_account_id end
  where first_account_id = least(v_account_id, p_requester_account_id)
    and second_account_id = greatest(v_account_id, p_requester_account_id)
    and requested_by = p_requester_account_id
    and status = 'pending'
    and deleted_at is null;
end
$$;

create or replace function public.remove_friend(p_friend_account_id bigint)
returns void language plpgsql security definer set search_path = '' as $$
declare
  v_account_id bigint := public.current_account_id();
  v_now timestamp with time zone := now();
begin
  if v_account_id is null then return; end if;
  update public.account_friend
  set updated_at = v_now,
      updated_by = v_account_id,
      deleted_at = v_now,
      deleted_by = v_account_id
  where first_account_id = least(v_account_id, p_friend_account_id)
    and second_account_id = greatest(v_account_id, p_friend_account_id)
    and deleted_at is null;

  update public.shopping_list_member as member
  set updated_at = v_now,
      updated_by = v_account_id,
      deleted_at = v_now,
      deleted_by = v_account_id
  from public.shopping_list as list
  where member.shopping_list_id = list.id
    and member.deleted_at is null
    and (
      (list.account_id = v_account_id
        and member.account_id = p_friend_account_id)
      or (list.account_id = p_friend_account_id
        and member.account_id = v_account_id)
    );

  update public.meal_plan_member as member
  set updated_at = v_now,
      updated_by = v_account_id,
      deleted_at = v_now,
      deleted_by = v_account_id
  from public.meal_plan as plan
  where member.meal_plan_id = plan.id
    and member.deleted_at is null
    and (
      (plan.account_id = v_account_id
        and member.account_id = p_friend_account_id)
      or (plan.account_id = p_friend_account_id
        and member.account_id = v_account_id)
    );
end
$$;

alter table public.meal_plan enable row level security;
alter table public.meal_plan_member enable row level security;
alter table public.meal_plan_entry enable row level security;
alter table public.shopping_list enable row level security;
alter table public.shopping_list_item enable row level security;
alter table public.shopping_list_member enable row level security;
alter table public.account_friend enable row level security;

drop policy if exists account_friend_participant_read
  on public.account_friend;
create policy account_friend_participant_read on public.account_friend
for select to authenticated using (
  first_account_id = public.current_account_id()
  or second_account_id = public.current_account_id()
);

drop policy if exists shopping_list_shared_read on public.shopping_list;
create policy shopping_list_shared_read on public.shopping_list
for select to authenticated using (public.can_discover_shopping_list(id));
drop policy if exists shopping_list_owner_insert on public.shopping_list;
create policy shopping_list_owner_insert on public.shopping_list
for insert to authenticated with check (
  public.current_account_can_write()
  and account_id = public.current_account_id()
  and created_by = public.current_account_id()
  and updated_by = public.current_account_id()
);
drop policy if exists shopping_list_owner_update on public.shopping_list;
create policy shopping_list_owner_update on public.shopping_list
for update to authenticated
using (account_id = public.current_account_id())
with check (
  account_id = public.current_account_id()
  and updated_by = public.current_account_id()
);
drop policy if exists shopping_list_owner_delete on public.shopping_list;
create policy shopping_list_owner_delete on public.shopping_list
for delete to authenticated using (account_id = public.current_account_id());

drop policy if exists shopping_list_item_shared on public.shopping_list_item;
create policy shopping_list_item_shared on public.shopping_list_item
for select to authenticated
using (public.can_view_shopping_list(shopping_list_id));
drop policy if exists shopping_list_item_shared_write
  on public.shopping_list_item;
create policy shopping_list_item_shared_write on public.shopping_list_item
for all to authenticated
using (public.can_edit_shopping_list(shopping_list_id))
with check (
  public.can_edit_shopping_list(shopping_list_id)
  and updated_by = public.current_account_id()
);

drop policy if exists shopping_list_member_read
  on public.shopping_list_member;
create policy shopping_list_member_read on public.shopping_list_member
for select to authenticated using (
  account_id = public.current_account_id()
  or exists (
    select 1 from public.shopping_list as list
    where list.id = shopping_list_id
      and list.account_id = public.current_account_id()
  )
  or (
    status = 'accepted'
    and public.can_view_shopping_list(shopping_list_id)
  )
);
drop policy if exists shopping_list_member_owner_write
  on public.shopping_list_member;

drop policy if exists meal_plan_read on public.meal_plan;
create policy meal_plan_read on public.meal_plan
for select to authenticated using (public.can_discover_meal_plan(id));
drop policy if exists meal_plan_owner_insert on public.meal_plan;
create policy meal_plan_owner_insert on public.meal_plan
for insert to authenticated with check (
  public.current_account_can_write()
  and account_id = public.current_account_id()
  and created_by = public.current_account_id()
  and updated_by = public.current_account_id()
);
drop policy if exists meal_plan_owner_update on public.meal_plan;
create policy meal_plan_owner_update on public.meal_plan
for update to authenticated
using (account_id = public.current_account_id())
with check (
  account_id = public.current_account_id()
  and updated_by = public.current_account_id()
);
drop policy if exists meal_plan_owner_delete on public.meal_plan;
create policy meal_plan_owner_delete on public.meal_plan
for delete to authenticated using (account_id = public.current_account_id());

drop policy if exists meal_plan_member_read on public.meal_plan_member;
create policy meal_plan_member_read on public.meal_plan_member
for select to authenticated using (
  account_id = public.current_account_id()
  or exists (
    select 1 from public.meal_plan as plan
    where plan.id = meal_plan_id
      and plan.account_id = public.current_account_id()
  )
  or (
    status = 'accepted'
    and public.can_view_meal_plan(meal_plan_id)
  )
);
drop policy if exists meal_plan_member_owner_write
  on public.meal_plan_member;

drop policy if exists meal_plan_entry_shared_read
  on public.meal_plan_entry;
create policy meal_plan_entry_shared_read on public.meal_plan_entry
for select to authenticated using (public.can_view_meal_plan(meal_plan_id));
drop policy if exists meal_plan_entry_shared_write
  on public.meal_plan_entry;
create policy meal_plan_entry_shared_write on public.meal_plan_entry
for all to authenticated
using (public.can_edit_meal_plan(meal_plan_id))
with check (
  public.can_edit_meal_plan(meal_plan_id)
  and updated_by = public.current_account_id()
);

revoke all on table public.meal_plan_member,
  public.shopping_list_member, public.account_friend
from public, anon, authenticated;
grant select on table public.meal_plan_member,
  public.shopping_list_member, public.account_friend to authenticated;
grant select, insert, update, delete on table public.meal_plan,
  public.meal_plan_entry, public.shopping_list,
  public.shopping_list_item to authenticated;
grant usage, select on sequence public.meal_plan_id_seq to authenticated;

revoke all on function public.can_discover_shopping_list(bigint),
  public.can_view_shopping_list(bigint),
  public.can_edit_shopping_list(bigint),
  public.can_discover_meal_plan(bigint),
  public.can_view_meal_plan(bigint),
  public.can_edit_meal_plan(bigint),
  public.set_shopping_list_member(bigint, bigint, text, boolean),
  public.respond_shopping_list_invitation(bigint, boolean),
  public.set_meal_plan_member(bigint, bigint, text, boolean),
  public.respond_meal_plan_invitation(bigint, boolean),
  public.send_friend_request(bigint),
  public.respond_friend_request(bigint, boolean),
  public.remove_friend(bigint)
from public, anon;
grant execute on function public.can_discover_shopping_list(bigint),
  public.can_view_shopping_list(bigint),
  public.can_edit_shopping_list(bigint),
  public.can_discover_meal_plan(bigint),
  public.can_view_meal_plan(bigint),
  public.can_edit_meal_plan(bigint),
  public.set_shopping_list_member(bigint, bigint, text, boolean),
  public.respond_shopping_list_invitation(bigint, boolean),
  public.set_meal_plan_member(bigint, bigint, text, boolean),
  public.respond_meal_plan_invitation(bigint, boolean),
  public.send_friend_request(bigint),
  public.respond_friend_request(bigint, boolean),
  public.remove_friend(bigint)
to authenticated;

do $$
declare
  table_name text;
begin
  foreach table_name in array array[
    'roles', 'account', 'account_friend', 'profiles', 'recipe', 'category', 'comment',
    'recipe_step', 'ingredient', 'recipe_ingredient',
    'recipe_step_ingredient', 'recipe_category', 'setting', 'recipe_like',
    'history', 'shopping_category', 'shopping_list', 'shopping_list_item',
    'shopping_list_member', 'meal_plan', 'meal_plan_member',
    'meal_plan_entry', 'meal_plan_template', 'meal_plan_template_entry'
  ] loop
    if to_regclass(format('public.%I', table_name)) is not null
      and not exists (
        select 1 from pg_publication_tables
        where pubname = 'supabase_realtime'
          and schemaname = 'public'
          and tablename = table_name
      ) then
      execute format(
        'alter publication supabase_realtime add table public.%I',
        table_name
      );
    end if;
  end loop;
end
$$;

notify pgrst, 'reload schema';
commit;
