-- Current meal-plan foundation for a fresh database. Plans belong to accounts
-- and can later be shared through meal_plan_member. No triggers or RPCs.
create table if not exists public.meal_plan (
  id bigint generated by default as identity not null,
  account_id bigint not null,
  name character varying not null,
  created_at timestamp with time zone not null default now(),
  created_by bigint not null,
  updated_at timestamp with time zone not null default now(),
  updated_by bigint not null,
  deleted_at timestamp with time zone null,
  deleted_by bigint null,
  constraint meal_plan_pkey primary key (id),
  constraint meal_plan_name_not_blank check (btrim(name) <> ''),
  constraint meal_plan_account_fkey foreign key (account_id)
    references public.account (id) on update cascade on delete cascade,
  constraint meal_plan_created_by_fkey foreign key (created_by)
    references public.account (id) on update cascade,
  constraint meal_plan_updated_by_fkey foreign key (updated_by)
    references public.account (id) on update cascade,
  constraint meal_plan_deleted_by_fkey foreign key (deleted_by)
    references public.account (id) on update cascade
);

create table if not exists public.meal_plan_entry (
  id bigint generated by default as identity not null,
  meal_plan_id bigint not null,
  planned_date date not null,
  meal_slot character varying not null,
  recipe_id bigint null,
  recipe_title_snapshot character varying null,
  custom_title character varying null,
  note character varying null,
  sort_order integer not null default 0,
  created_at timestamp with time zone not null default now(),
  created_by bigint not null,
  updated_at timestamp with time zone not null default now(),
  updated_by bigint not null,
  deleted_at timestamp with time zone null,
  deleted_by bigint null,
  constraint meal_plan_entry_pkey primary key (id),
  constraint meal_plan_entry_plan_fkey foreign key (meal_plan_id)
    references public.meal_plan (id) on update cascade on delete cascade,
  constraint meal_plan_entry_recipe_id_fkey foreign key (recipe_id)
    references public.recipe (id) on update cascade,
  constraint meal_plan_entry_created_by_fkey foreign key (created_by)
    references public.account (id) on update cascade,
  constraint meal_plan_entry_updated_by_fkey foreign key (updated_by)
    references public.account (id) on update cascade,
  constraint meal_plan_entry_deleted_by_fkey foreign key (deleted_by)
    references public.account (id) on update cascade,
  constraint meal_plan_entry_slot_check check (
    meal_slot in ('breakfast', 'lunch', 'dinner', 'snack')
  ),
  constraint meal_plan_entry_content_check check (
    (recipe_id is not null and custom_title is null) or
    (
      recipe_id is null and
      custom_title is not null and
      btrim(custom_title) <> ''
    ) or
    (
      recipe_id is null and
      custom_title is null and
      nullif(btrim(recipe_title_snapshot), '') is not null
    )
  ),
  constraint meal_plan_entry_sort_order_check check (sort_order >= 0)
);

create index if not exists meal_plan_entry_plan_date_idx
  on public.meal_plan_entry (meal_plan_id, planned_date, meal_slot, sort_order)
  where deleted_at is null;
